CONTROL	TextEditor
{
   TYPE	icon
   CONTAINER_TYPE	BOX
   CONTAINER_NAME	Top
   POSITION_HINTS	4
   ICON	Fpterm
   LABEL	Terminal
   PUSH_ACTION	Terminal
   HELP_VOLUME	FPanel
   HELP_TOPIC	FPOnItemTerm
}
